upgrade.report.enabled=false
auto.deploy.listeners=\
    com.liferay.portal.deploy.auto.HookAutoDeployListener,\
    com.liferay.portal.deploy.auto.LayoutTemplateAutoDeployListener,\
    com.liferay.portal.deploy.auto.PortletAutoDeployListener,\
    com.liferay.portal.deploy.auto.ThemeAutoDeployListener,\
    com.liferay.portal.deploy.auto.WebAutoDeployListener
auto.deploy.enabled=

hot.deploy.listeners=\
    com.liferay.portal.deploy.hot.PluginPackageHotDeployListener,\
    \
    com.liferay.portal.deploy.hot.ServletContextListenerHotDeployListener,\
    \
    com.liferay.portal.deploy.hot.HookHotDeployListener,\
    com.liferay.portal.deploy.hot.JSONWebServiceHotDeployListener,\
    com.liferay.portal.deploy.hot.LayoutTemplateHotDeployListener,\
    com.liferay.portal.deploy.hot.PortletHotDeployListener,\
    com.liferay.portal.deploy.hot.SocialHotDeployListener,\
    com.liferay.portal.deploy.hot.ThemeHotDeployListener,\
    com.liferay.portal.deploy.hot.ThemeLoaderHotDeployListener,\
    \
    com.liferay.portal.deploy.hot.OSGiHotDeployListener

portlet.add.default.resource.check.whitelist=\
    com_liferay_calendar_web_portlet_CalendarPortlet,\
    com_liferay_login_web_portlet_FastLoginPortlet,\
    com_liferay_login_web_portlet_LoginPortlet,\
    com_liferay_portlet_configuration_css_web_portlet_PortletConfigurationCSSPortlet,\
    com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet,\
    com_liferay_product_navigation_simulation_web_portlet_SimulationPortlet,\
    com_liferay_staging_bar_web_portlet_StagingBarPortlet
module.framework.base.dir=${liferay.home}/osgi
module.framework.file.install.subdir.mode1=skip
module.framework.properties.lpkg.index.validator.enabled=false
module.framework.properties.osgi.console=0.0.0.0:11311
notification.email.template.enabled=true
dl.char.blacklist=\\\\,//,:,*,?,\",<,>,|,../,/..

redirect.url.domains.allowed=localhost,SERVER_IP
redirect.url.security.mode=domain

configuration.override.com.liferay.frontend.js.web.internal.session.timeout.configuration.SessionTimeoutConfiguration_autoExtendOffset=I"300"
configuration.override.com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.document.configuration.BulkDocumentRequestRetryConfiguration_numberOfTries=I"5"