apiVersion: v2
appVersion: latest
description:
    Liferay is an all-in-one DXP, LCAP, and Commerce platform. This chart creates cloud agnostic observability resources to help monitor your Liferay stack.
icon: https://www-cdn.liferay.com/documents/d/guest/liferay-logo
name: observability
type: application
version: 0.1.0