upgrade.AnalysisReportCheck.fileTypes=\
    .ftl,\
    .java,\
    .jsp,\
    .properties,\
    .xml,\
    build.gradle,\
    Language**.properties,\
    portal**.properties,\
    service.xml,\
    settings.gradle